spring.application.name=ShoeStoreManagement
spring.datasource.url=jdbc:mysql://localhost:3306/shoe_store_management
spring.datasource.username=root
spring.datasource.password=phat2026@
spring.jpa.hibernate.ddl-auto=update
server.port=8080